/*-
 * Copyright (c) 2014 Rui Paulo <rpaulo@felyko.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <stdio.h>

#include <libpru.h>


/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

static const unsigned int PRUcode[] =  {
     0x00e2e1e0,
     0x01c8e1e0,
     0x02e2e1ff,
     0x03c8e1ff,
     0x04e2e1e0,
     0x050ae1e0,
     0x06e2e1e0,
     0x0714e1e0,
     0x0ee2e1e0,
     0x0f0ae1e1,
     0x0ce2e1e0,
     0x0d14e1e1,
     0x0901e1e0,
     0x0801e0e0,
     0x090a03e3,
     0x0b01e1e0,
     0x0a03e1e0,
     0x0b01e1e0,
     0x10e2e1e0,
     0x10c201e3,
     0x12e2e1e0,
     0x12c201e3,
     0x13080303,
     0x14e2e1e0,
     0x14c201e3,
     0x15080303,
     0x1700e1e0,
     0x18e2e1e0,
     0x1ae2e1e0,
     0x1ce1e0e0,
     0x1ee2e1e0,
     0x26e2e1e0,
     0x10e1e1e0,
     0x10e5e5e4,
     0x240001e0,
     0x2c2001e0,
     0x2c2101e0,
     0x2c2201e0,
     0xf1010180,
     0xe1010180,
     0x91010080,
     0x81010080,
     0x2eff8380,
     0x2eff0380,
     0x2e800380,
     0x2f000380,
     0x2f800380,
     0x20800000,
     0x20810000,
     0x22c00080,
     0x22c10081,
     0x2280009e,
     0x2281009e,
     0x209e0000,
     0x61018009,
     0x71018008,
     0x49018007,
     0x59018006,
     0x51018005,
     0x69018004,
     0x79000003,
     0xd0e1e002,
     0xc8e1e001,
     0xc8e0ff00,
     0xd0e0ff00,
     0x2a000000,
     0x3e000000,
     0x10000000,
     0x3e800000,
     0x10000000 };



int
main()
{
	char buf[100];

	for (unsigned int i = 0; i < sizeof(PRUcode) / 4; i++) {
		ti_disassemble(PRUcode[i], buf, 100);
		printf("%s\n", buf);
	}
}
